In [ ]:
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Summer training 2026/DataSet 2026/heart.csv')

In [ ]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0


In [ ]:
df.shape

(1025, 14)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [ ]:
df["target"].value_counts()

,count
target,
1,526
0,499


In [ ]:
df["target"].value_counts(normalize=True) * 100

,proportion
target,
1,51.317073
0,48.682927


In [ ]:
df.isnull().sum()

,0
age,0
sex,0
cp,0
trestbps,0
chol,0
fbs,0
restecg,0
thalach,0
exang,0
oldpeak,0


In [ ]:
df.duplicated().sum()

np.int64(723)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(302, 14)

In [ ]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,302.00000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000
mean,54.42053,0.682119,0.963576,131.602649,246.500000,0.149007,0.526490,149.569536,0.327815,1.043046,1.397351,0.718543,2.314570,0.543046
std,9.04797,0.466426,1.032044,17.563394,51.753489,0.356686,0.526027,22.903527,0.470196,1.161452,0.616274,1.006748,0.613026,0.498970
min,29.00000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.00000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.250000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.50000,1.000000,1.000000,130.000000,240.500000,0.000000,1.000000,152.500000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.00000,1.000000,2.000000,140.000000,274.750000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.00000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000


In [ ]:
x = df.drop("target", axis=1)
y = df["target"]

In [ ]:
print(x.shape)
print(y.shape)

(302, 13)
(302,)


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (241, 13)
X_test : (61, 13)
y_train: (241,)
y_test : (61,)


In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
print(X_train_scaled.shape)
print(X_test_scaled.shape)

(241, 13)
(61, 13)


In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7704918032786885


In [ ]:
from sklearn.metrics import accuracy_score

train_pred = model.predict(X_train_scaled)
test_pred = model.predict(X_test_scaled)
train_accuracy = accuracy_score(y_train, train_pred)
test_accuracy = accuracy_score(y_test, test_pred)

print("Training Accuracy :", train_accuracy)
print("Testing Accuracy  :", test_accuracy)

Training Accuracy : 0.8630705394190872
Testing Accuracy  : 0.7704918032786885


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[21 11]
 [ 3 26]]

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.66      0.75        32
           1       0.70      0.90      0.79        29

    accuracy                           0.77        61
   macro avg       0.79      0.78      0.77        61
weighted avg       0.79      0.77      0.77        61



# **Deep Learning Model**

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
dl_model = Sequential([
    Dense(16, activation='relu', input_shape=(13,)),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
dl_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
history = dl_model.fit(X_train_scaled,y_train,epochs=50,batch_size=16,validation_data=(X_test_scaled, y_test),verbose=1)

Epoch 1/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 6s 77ms/step - accuracy: 0.5892 - loss: 0.6930 - val_accuracy: 0.4754 - val_loss: 0.8272
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - accuracy: 0.6224 - loss: 0.6400 - val_accuracy: 0.5902 - val_loss: 0.7731
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6763 - loss: 0.6033 - val_accuracy: 0.6393 - val_loss: 0.7388
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7178 - loss: 0.5734 - val_accuracy: 0.6393 - val_loss: 0.7142
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7510 - loss: 0.5461 - val_accuracy: 0.6721 - val_loss: 0.6838
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7801 - loss: 0.5207 - val_accuracy: 0.7049 - val_loss: 0.6633
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7884 - loss: 0.4992 - val_accuracy: 0.7049 - val_loss: 0.6437
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7967 - loss: 0.4780 - val_accuracy: 0.7213 - v

In [ ]:
train_pred_prob = dl_model.predict(X_train_scaled)
train_pred_dl = (train_pred_prob > 0.5).astype(int)


test_pred_prob = dl_model.predict(X_test_scaled)
test_pred_dl = (test_pred_prob > 0.5).astype(int)

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step 
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


In [ ]:
from sklearn.metrics import accuracy_score

print("DL Train Accuracy :", accuracy_score(y_train, train_pred_dl))
print("DL Test Accuracy  :", accuracy_score(y_test, test_pred_dl))

DL Train Accuracy : 0.8630705394190872
DL Test Accuracy  : 0.7704918032786885


In [ ]:
from sklearn.metrics import confusion_matrix

print("Train Confusion Matrix")
print(confusion_matrix(y_train, train_pred_dl))

print("\nTest Confusion Matrix")
print(confusion_matrix(y_test, test_pred_dl))

Train Confusion Matrix
[[ 88  18]
 [ 15 120]]

Test Confusion Matrix
[[24  8]
 [ 6 23]]


In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, test_pred_dl))

              precision    recall  f1-score   support

           0       0.80      0.75      0.77        32
           1       0.74      0.79      0.77        29

    accuracy                           0.77        61
   macro avg       0.77      0.77      0.77        61
weighted avg       0.77      0.77      0.77        61



In [ ]:
train_loss, train_accuracy = dl_model.evaluate(X_train_scaled, y_train, verbose=0)
test_loss, test_accuracy = dl_model.evaluate(X_test_scaled, y_test, verbose=0)
print("Training Accuracy:", train_accuracy)
print("Testing Accuracy :", test_accuracy)

Training Accuracy: 0.863070547580719
Testing Accuracy : 0.7704917788505554


In [ ]:
print('Train Precision :-',precision_score(y_train,train_pred))
print('Test Precision :-',precision_score(y_test,test_pred))

Train Precision :- 0.8493150684931506
Test Precision :- 0.7027027027027027


In [ ]:
print('Train Recall :-',recall_score(y_train,train_pred))
print('Test Recall :-',recall_score(y_test,test_pred))

Train Recall :- 0.9185185185185185
Test Recall :- 0.896551724137931
